### ISSUE TITLE
Bug in daily projections

### ISSUE THREAD

**Issue by zulcss** [Big-Life-Lab/Ottawa-COVID-Projection#26]
The case projections seem to be a bit off maybe?
![bug](https://user-images.githubusercontent.com/319235/100624202-2689bc00-32f1-11eb-8e55-2ff79b46fbfa.png)

**Comment by zulcss** [comment]
Nevermind figured it out.

**Comment by DougManuel** [comment]
I received a similar or same question by Twitter. https://twitter.com/YoniFreedhoff/status/1333487783013445632

 Rt has just started to bounce around 1.0 -- means the short-term projections are really unstable with wide confidence boundaries. The shaded area is 90% credible projection for next week.

**Comment by zulcss** [comment]
I saw the same tweet this morning.
